name: Lint
on: [push, pull_request]
jobs:
  eslint_and_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - name: Install dependencies
        run: npm install
      - name: Eslint
        run: npm run lint:fix
      - name: Prettier
        run: npm run format:check
